### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by jayvdb** [astamminger/pypi_downloader#1]
Do you plan to publish this onto PyPI?

It seems to have similar intentions as https://github.com/AbdealiJK/pip-downloader and https://github.com/youngquan/pip-download

**Comment by astamminger** [comment]
Dear @jayvdb ,

apologies for the very late response!
>
> Do you plan to publish this onto PyPI?
>
Well, I implemented this thing merely to work around a limitation on a cluster that has been resolved in the meantime. So, for now I do not have any plans to publish this onto PyPI.
>
> It seems to have similar intentions as https://github.com/AbdealiJK/pip-downloader and https://github.com/youngquan/pip-download
>
I am not sure if these packages were around when I originally implemented this downloader utility. At least i can't remember that these popped up when I searched for some downloader doing the thing I needed.

Cheers,
Andreas

**Comment by jayvdb** [comment]
Thanks for getting back to me.  Both of those packages are progressing, and my own needs turned out to be best solved with https://github.com/jerith/landinggear , so no need to have this issue open if you're not actively using & developing it.
